name: 🔒 Security Vulnerability
description: Report a security vulnerability (PRIVATE - use GitHub Security Advisories instead)
title: "[Security]: "
labels: ["security"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # ⚠️ STOP - Please Read Carefully
        
        **DO NOT use this public issue template for security vulnerabilities!**
        
        Public disclosure of security vulnerabilities puts users at risk.
        
        ## Please Report Security Issues Through:
        
        ### 🐛 GitHub Security Advisories (RECOMMENDED)
        
        1. Go to the [Security tab](https://github.com/V1B3hR/nethical-recon/security/advisories)
        2. Click "Report a vulnerability"
        3. Fill out the private security advisory form
        
        ### 📧 Email (Alternative)
        
        - **Email**: security@nethical-recon.example
        - **PGP Key**: See [SECURITY.md](../../SECURITY.md)
        
        ## Our Security Policy
        
        Please review our complete security policy: [SECURITY.md](../../SECURITY.md)
        
        **Response Timeline:**
        - ✅ 24 hours: Initial acknowledgment
        - ✅ 7 days: Severity assessment
        - ✅ 30 days: Preliminary fix or mitigation
        - ✅ 90 days: Public disclosure (coordinated)
        
        ## Safe Harbor Policy
        
        We support good-faith security research and will not pursue legal action against researchers who:
        
        ✅ Make good-faith effort to avoid privacy violations and service disruption  
        ✅ Only interact with accounts you own or have permission to test  
        ✅ Do not exploit vulnerability beyond demonstration  
        ✅ Give us reasonable time to fix before public disclosure  
        ✅ Do not access, modify, or delete data belonging to others  
        
        ## Recognition
        
        Valid security reports will be acknowledged in our security hall of fame (with your permission).
        
        ## What to Include in Your Report
        
        - **Vulnerability Type**: SQL injection, XSS, authentication bypass, etc.
        - **Affected Version(s)**: Specific version numbers
        - **Steps to Reproduce**: Detailed steps to demonstrate the vulnerability
        - **Proof of Concept**: Working PoC code or demonstration
        - **Impact Assessment**: What can an attacker do?
        - **Suggested Fix**: If you have ideas for remediation
        
        ## Thank You!
        
        Thank you for helping us keep Nethical Recon secure! 🙏
        
        ---

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm you understand
      options:
        - label: I understand that I should NOT use this public template for real security vulnerabilities
          required: true
        - label: I will use GitHub Security Advisories or email security@nethical-recon.example instead
          required: true
        - label: I have read the Security Policy in SECURITY.md
          required: true

  - type: markdown
    attributes:
      value: |
        ## If you continue past this point, this is NOT a private security report
        
        This form can be used for:
        - Security-related questions (not vulnerabilities)
        - Security documentation improvements
        - Security feature requests
        - Clarifications about the security policy
        
        **For actual vulnerabilities, please stop and use the methods above!**

  - type: dropdown
    id: inquiry-type
    attributes:
      label: Type of Security Inquiry
      description: What type of security-related inquiry is this?
      options:
        - Security Policy Question
        - Security Documentation Improvement
        - Security Feature Request
        - Security Best Practices Question
        - Other Security Question
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your security-related inquiry
      placeholder: |
        Please describe your question or suggestion
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information
      placeholder: Add any other relevant information
