"""
🦅 Base Bird Class - Foundation for all Sky Surveillance Birds

> "Every bird has its unique way of watching over the forest"
"""

from abc import ABC, abstractmethod
from datetime import datetime
from enum import Enum
from typing import Any


class BirdType(Enum):
    """Types of surveillance birds"""

    EAGLE = "eagle"  # 🦅 Strategic command & overview
    FALCON = "falcon"  # 🦅 Fast response & real-time alerts
    OWL = "owl"  # 🦉 Night watch & stealth monitoring
    SPARROW = "sparrow"  # 🐦 Routine checks & heartbeat


class FlightMode(Enum):
    """Bird flight modes"""

    SOARING = "soaring"  # High altitude overview (Eagle)
    HUNTING = "hunting"  # Active pursuit (Falcon)
    WATCHING = "watching"  # Stealth observation (Owl)
    PATROLLING = "patrolling"  # Regular rounds (Sparrow)
    RESTING = "resting"  # Inactive/standby
    EMERGENCY = "emergency"  # Critical response mode


class AlertLevel(Enum):
    """Alert severity levels"""

    INFO = ("info", "🟢", "chirp")  # Routine information
    WARNING = ("warning", "🟡", "hoot")  # Unusual activity
    ELEVATED = ("elevated", "🟠", "screech")  # Suspicious behavior
    CRITICAL = ("critical", "🔴", "roar")  # Active threat
    BREACH = ("breach", "⚫", "caw")  # Confirmed compromise

    def __init__(self, level, emoji, sound):
        self.level = level
        self.emoji = emoji
        self.sound = sound


class BirdAlert:
    """Alert generated by a bird"""

    def __init__(
        self,
        bird_type: BirdType,
        level: AlertLevel,
        message: str,
        location: dict[str, str] | None = None,
        evidence: list[str] | None = None,
        timestamp: datetime | None = None,
    ):
        self.bird_type = bird_type
        self.level = level
        self.message = message
        self.location = location or {}
        self.evidence = evidence or []
        self.timestamp = timestamp or datetime.now()

    def to_dict(self) -> dict[str, Any]:
        """Convert alert to dictionary"""
        return {
            "bird_type": self.bird_type.value,
            "level": self.level.level,
            "emoji": self.level.emoji,
            "sound": self.level.sound,
            "message": self.message,
            "location": self.location,
            "evidence": self.evidence,
            "timestamp": self.timestamp.isoformat(),
        }

    def __str__(self) -> str:
        """String representation of alert"""
        bird_emoji = {BirdType.EAGLE: "🦅", BirdType.FALCON: "🦅", BirdType.OWL: "🦉", BirdType.SPARROW: "🐦"}
        time_str = self.timestamp.strftime("%H:%M")
        emoji = bird_emoji.get(self.bird_type, "🐦")
        return f"{emoji} {time_str} [{self.level.sound.upper()}] {self.bird_type.value.title()}: {self.message}"


class BaseBird(ABC):
    """
    Abstract base class for all surveillance birds

    Each bird type has unique capabilities for monitoring the forest:
    - 🦅 Eagle: Strategic overview from highest altitude
    - 🦅 Falcon: Fast response with sharp vision
    - 🦉 Owl: Night-time stealth monitoring
    - 🐦 Sparrow: Routine health checks
    """

    def __init__(self, name: str, bird_type: BirdType):
        """
        Initialize a bird

        Args:
            name: Bird's identifier name
            bird_type: Type of bird (Eagle, Falcon, Owl, Sparrow)
        """
        self.name = name
        self.bird_type = bird_type
        self.flight_mode = FlightMode.RESTING
        self.is_active = False
        self.alerts: list[BirdAlert] = []
        self.observations: list[dict[str, Any]] = []
        self.patrol_area: dict[str, Any] | None = None
        self.last_patrol: datetime | None = None

    @abstractmethod
    def scan(self, forest_data: dict[str, Any]) -> list[BirdAlert]:
        """
        Scan the forest for threats and anomalies

        Args:
            forest_data: Current state of the forest

        Returns:
            List of alerts generated from scan
        """
        pass

    @abstractmethod
    def get_capabilities(self) -> dict[str, str]:
        """
        Get bird's unique capabilities

        Returns:
            Dictionary of capability descriptions
        """
        pass

    def take_flight(self, mode: FlightMode):
        """Start bird patrol in specified mode"""
        self.is_active = True
        self.flight_mode = mode
        self.last_patrol = datetime.now()

    def land(self):
        """Stop bird patrol"""
        self.is_active = False
        self.flight_mode = FlightMode.RESTING

    def set_patrol_area(self, area: dict[str, Any]):
        """
        Set the area this bird should patrol

        Args:
            area: Dictionary defining patrol territory
        """
        self.patrol_area = area

    def create_alert(
        self,
        level: AlertLevel,
        message: str,
        location: dict[str, str] | None = None,
        evidence: list[str] | None = None,
    ) -> BirdAlert:
        """
        Create and store an alert

        Args:
            level: Severity level
            message: Alert description
            location: Where the alert was detected
            evidence: Supporting evidence

        Returns:
            Created alert object
        """
        alert = BirdAlert(bird_type=self.bird_type, level=level, message=message, location=location, evidence=evidence)
        self.alerts.append(alert)
        return alert

    def get_recent_alerts(self, count: int = 10) -> list[BirdAlert]:
        """Get most recent alerts"""
        return self.alerts[-count:] if self.alerts else []

    def clear_old_alerts(self, max_age_hours: int = 24):
        """Remove alerts older than specified hours"""
        cutoff = datetime.now().timestamp() - (max_age_hours * 3600)
        self.alerts = [alert for alert in self.alerts if alert.timestamp.timestamp() > cutoff]

    def get_status(self) -> dict[str, Any]:
        """Get current bird status"""
        return {
            "name": self.name,
            "type": self.bird_type.value,
            "active": self.is_active,
            "flight_mode": self.flight_mode.value,
            "alert_count": len(self.alerts),
            "last_patrol": self.last_patrol.isoformat() if self.last_patrol else None,
            "patrol_area": self.patrol_area,
            "capabilities": self.get_capabilities(),
        }

    def __str__(self) -> str:
        """String representation of bird"""
        status = "ACTIVE" if self.is_active else "RESTING"
        return f"{self.bird_type.value.upper()} '{self.name}' [{status}] - {self.flight_mode.value}"

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__}(name='{self.name}', type={self.bird_type.value})>"
